# Generated by Django 4.2 on 2025-08-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_excerpt_post_content_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='tbl_posts',
        ),
    ]
